/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class PdfCore {
  constructor()
  /** Load a PDF from raw bytes. Returns an opaque document id. */
  loadPdf(bytes: Buffer): number
  /** Close a previously loaded document. */
  close(id: number): void
  pageCount(id: number): number
  /** Page size in PDF points (72 dpi). */
  pageSize(id: number, index: number): PageSize
  /** Render a page at the given scale (1.0 == 72 dpi). Returns RGBA. */
  renderPage(id: number, index: number, scale: number): RenderedPage
  /** Render a page thumbnail (max dimension = size pixels). */
  renderThumbnail(id: number, index: number, size: number): RenderedPage
  /** Text line segments on a page with rects (PDF points, top-left origin). */
  getTextItems(id: number, index: number): Array<TextItem>
  /** Case-insensitive search across the whole document. */
  search(id: number, query: string): Array<SearchHit>
  listFonts(id: number): Array<FontInfo>
  /** Return embedded font file bytes (TTF/OTF/CFF) for the named font. */
  getFont(id: number, name: string): Buffer
}

export interface FontInfo {
  name: string
  isEmbedded: boolean
}

export interface PageSize {
  width: number
  height: number
}

export interface RenderedPage {
  width: number
  height: number
  /** RGBA pixel data, row-major, width * height * 4 bytes. */
  rgba: Buffer
}

export interface SearchHit {
  page: number
  x: number
  y: number
  width: number
  height: number
}

export interface TextItem {
  text: string
  /** Rect in PDF points, origin top-left (converted from PDF coords). */
  x: number
  y: number
  width: number
  height: number
  fontSize: number
  fontName?: string
}
